version: "2"
services:
  srly-ose-server:
    image: screenly/srly-ose-server:latest
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 80:8080
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  srly-ose-viewer:
    image: screenly/srly-ose-viewer:latest-pi3
    depends_on:
      - srly-ose-server
    environment:
      - HOME=/data
      - NOREFRESH=1
      - PORT=80
    network_mode: "host"
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  srly-ose-websocket:
    image: screenly/srly-ose-websocket:latest
    depends_on:
      - srly-ose-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    ports:
      - 9999:9999
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  srly-ose-celery:
    image: screenly/srly-ose-celery:latest
    depends_on:
      - srly-ose-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  redis:
    image: screenly/srly-ose-redis:latest
    restart: always

volumes:
    resin-data:
