version: "3"
services:
  screenly-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server.dev
    environment:
      - PYTHONUNBUFFERED=1
      - LISTEN=0.0.0.0
    image: screenly-ose-server
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/pi/screenly:ro
      - screenly-volume:/home/pi/.screenly
      - screenly-assets-volume:/home/pi/screenly_assets

  screenly-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket.dev
    depends_on:
      - screenly-server
    image: screenly-ose-websocket
    network_mode: "host"
    volumes:
      - ./:/home/pi/screenly:ro
      - screenly-volume:/home/pi/.screenly
      - screenly-assets-volume:/home/pi/screenly_assets

  screenly-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery.dev
    depends_on:
      - redis
      - screenly-server
    image: screenly-ose-celery
    network_mode: "host"
    volumes:
      - ./:/home/pi/screenly:ro
      - screenly-volume:/home/pi/.screenly
      - screenly-assets-volume:/home/pi/screenly_assets

  redis:
    restart: always
    image: redis:alpine
    expose:
      - 6379
    logging:
      driver: none

volumes:
  screenly-volume:
  screenly-assets-volume:
