# This is the docker-compose file for Balena.
version: "2"
services:
  screenly-ose-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server.template
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - PYTHONPATH=/data/screenly
      - SCREENLYSERVICE=server
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 80:8080
    privileged: true
    restart: always
    volumes:
      - resin-data:/data

  screenly-ose-viewer:
    build:
      context: .
      dockerfile: docker/Dockerfile.viewer.template
    depends_on:
      - screenly-ose-server
    environment:
      - HOME=/data
      - NOREFRESH=1
      - PYTHONPATH=/data/screenly
      - SCREENLYSERVICE=viewer
      - LISTEN=screenly-ose-server
      - PORT=80
      - QT_QPA_PLATFORM=eglfs
    network_mode: "host"
    privileged: true
    restart: always
    volumes:
      - resin-data:/data

  screenly-ose-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket.template
    depends_on:
      - screenly-ose-server
    environment:
      - HOME=/data
      - PYTHONPATH=/data/screenly
      - SCREENLYSERVICE=websocket
      - LISTEN=screenly-ose-server
    ports:
      - 9999:9999
    privileged: true
    restart: always
    volumes:
      - resin-data:/data

  screenly-ose-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - screenly-ose-server
      - redis
    environment:
      - HOME=/data
      - PYTHONPATH=/data/screenly
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    privileged: true
    restart: always
    volumes:
      - resin-data:/data

  redis:
    build:
      context: .
      dockerfile: docker/Dockerfile.redis.template
    restart: always

volumes:
    resin-data:
