version: "2"
services:
  srly-ose-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 80:8080
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
  srly-ose-viewer:
    build:
      context: .
      dockerfile: docker/Dockerfile.viewer.bak
    depends_on:
      - srly-ose-server
    environment:
      - HOME=/data
      - NOREFRESH=1
      - PORT=80
    network_mode: "host"
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
  srly-ose-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    depends_on:
      - srly-ose-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    ports:
      - 9999:9999
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
  srly-ose-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - srly-ose-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
  redis:
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    restart: always

volumes:
    resin-data:
