version: "2.2"
services:
  srly-ose-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEVELOPMENT_MODE=1
      - FLASK_APP=server.py
      - FLASK_ENV=development
    restart: always
    volumes:
      - resin-data:/data
      - ./:/usr/src/app/

# We might bring this in in the future
#  srly-ose-viewer:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.viewer
#    depends_on:
#      - srly-ose-server
#    environment:
#      - HOME=/data
#      - PORT=80
#      - NOREFRESH=1
#      - LISTEN=srly-ose-nginx
#    privileged: true
#    restart: always
#    volumes:
#      - resin-data:/data

  srly-ose-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    depends_on:
      - srly-ose-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    restart: always
    volumes:
      - resin-data:/data

  srly-ose-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - srly-ose-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always
    volumes:
      - resin-data:/data

  redis:
    platform: "linux/amd64"
    image: redis:alpine

  srly-ose-nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 8000:80
    environment:
      - HOME=/data
    depends_on:
      - srly-ose-server
      - srly-ose-websocket
    restart: always
    volumes:
      - resin-data:/data:ro

volumes:
    resin-data:
    redis-data:
