version: "2"
services:
  screenly-server:
    build:
      context: .
      dockerfile: Dockerfile.server.template
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - PYTHONPATH=/data/screenly
      - SWAGGER_HOST=ose.demo.screenlyapp.com
    network_mode: "host"
    privileged: true
    volumes:
      - resin-data:/data

  screenly-viewer:
    build:
      context: .
      dockerfile: Dockerfile.viewer.template
    depends_on:
      - screenly-server
    environment:
      - DISABLE_UPDATE_CHECK=True
      - DISPLAY=:0.0
      - HOME=/data
      - NOREFRESH=1
      - PYTHONPATH=/data/screenly
    network_mode: "host"
    privileged: true
    volumes:
      - resin-data:/data

  screenly-websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket.template
    depends_on:
      - screenly-server
    environment:
      - HOME=/data
      - PYTHONPATH=/data/screenly
    network_mode: "host"
    privileged: true
    volumes:
      - resin-data:/data

volumes:
    resin-data:
