- name: Install Screenly
  hosts: all
  user: pi
  become: yes
  vars:
    manage_network: "{{ lookup('env', 'MANAGE_NETWORK') }}"
    docker_tag: "{{ lookup('env', 'DOCKER_TAG') }}"
    device_type: "{{ lookup('env', 'DEVICE_TYPE') }}"

  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted

    - name: reload systemctl
      command: systemctl daemon-reload

    - name: restart-screenly-websocket_server_layer
      command: systemctl restart screenly-websocket_server_layer.service

    - name: restart-screenly-server
      command: systemctl restart screenly-web.service

    - name: restart-screenly-celery
      command: systemctl restart screenly-celery.service

  roles:
    - system
    - rpi-update
    - screenly
    - network
    - splashscreen
    - nginx
    - ssl
    - tools
