name: Build Balena Disk Images
on: workflow_dispatch
jobs:
  balena-build-images:
    strategy:
      matrix:
        board: ['pi1', 'pi2', 'pi3', 'pi4']
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get base board
        run: |
          if [ "${{ matrix.board }}" == 'pi1' ]; then
            echo "BALENA_IMAGE=raspberry-pi" >> $GITHUB_ENV
          elif [ "${{ matrix.board }}" == 'pi2' ]; then
            echo "BALENA_IMAGE=raspberry-pi2" >> $GITHUB_ENV
          elif [ "${{ matrix.board }}" == 'pi3' ]; then
            echo "BALENA_IMAGE=raspberrypi3" >> $GITHUB_ENV
          elif [ "${{ matrix.board }}" == 'pi4' ]; then
            echo "BALENA_IMAGE=raspberrypi4-64" >> $GITHUB_ENV
          fi

      - name: balena CLI Action - download
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            os download "$BALENA_IMAGE" \
              --output "$BALENA_IMAGE.img" \
              --version default
          balena_cli_version: 13.7.1

      - name: balena CLI Action - preload
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            preload \
              "$BALENA_IMAGE.img" \
              --fleet screenly_ose/screenly-ose-${{ matrix.board }} \
              --commit latest
          balena_cli_version: 13.7.1

      - name: balena CLI Action - configure
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            os configure \
              "$BALENA_IMAGE.img" \
              --config-network=ethernet  \
              --fleet screenly_ose/screenly-ose-${{ matrix.board }}
          balena_cli_version: 13.7.1

      - name: Zip image
        run: |
          zip -9 \
            "$(date -I)-$BALENA_IMAGE.zip" \
            "$BALENA_IMAGE.img"

      - uses: ncipollo/release-action@@v1.11.2
        with:
          prerelease: true
          artifacts: "*.zip"
