name: Build Balena Disk Images
on: workflow_dispatch
jobs:
  balena-build-images:
    strategy:
      matrix:
        # board: ['pi1', 'pi2', 'pi3', 'pi4']
        board: ['pi3', 'pi4']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get base board
        run: |
          # Logic for Raspberry Pi 1
          if [ "${{ matrix.board }}" == 'pi1' ]; then
            echo "BALENA_IMAGE=raspberry-pi" >> $GITHUB_ENV
          # Logic for Raspberry Pi 2
          elif [ "${{ matrix.board }}" == 'pi2' ]; then
            echo "BALENA_IMAGE=raspberry-pi2" >> $GITHUB_ENV
          else
            echo "BALENA_IMAGE=raspberrypi3" >> $GITHUB_ENV
          fi

      - name: balena CLI Action
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            download "$BALENA_IMAGE" \
              --output "$BALENA_IMAGE.img" \
              --version default;
            preload \
              "$BALENA_IMAGE.img" \
              --fleet screenly_ose/screenly-ose-${{ matrix.board }} \
              --commit latest
          balena_cli_version: 13.7.1

      - name: Zip image
        run: |
          zip -9 \
            "$BALENA_IMAGE.zip" \
            "$BALENA_IMAGE.img"

      - uses: actions/upload-artifact@v3
        with:
          name: Release file
          path: "$BALENA_IMAGE.zip"
