name: Docker Image Build

on:
  push:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

     #- name: Login to DockerHub
     #  if: success() && github.event_name != 'pull_request'
     #  uses: docker/login-action@v1
     #  with:
     #    username: ${{ secrets.DOCKER_USERNAME }}
     #    password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tag and buildx args
        id: prepare
        run: |
          if [ "$GITHUB_REF_NAME" == 'master' ]; then
             export 'DOCKER_TAG=latest';
          elif [ "$GITHUB_REF_NAME" == 'production' ]; then
             export 'DOCKER_TAG=production';
          fi
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

          echo ::set-output name=buildx_args::\
            --platform linux/arm/v6,linux/arm/v7 \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --build-arg "GIT_HASH=$GITHUB_SHA" \
            --build-arg "GIT_SHORT_HASH=$(git rev-parse --short HEAD)" \
            --build-arg "GIT_BRANCH=$GITHUB_REF_NAME"

      - name: Building base container
        run: |
          docker buildx build \
            ${{ steps.prepare.outputs.buildx_args }} \
            -f "docker/Dockerfile.base" \
            -t "screenly/srly-ose-base:$DOCKER_TAG" .

      # We need to Clean up and refactor the blow to use concurrencty.
      - name: Building server container
        run: |
          docker buildx build \
            ${{ steps.prepare.outputs.buildx_args }} \
            -f "docker/Dockerfile.server" \
            -t "screenly/srly-ose-server:$DOCKER_TAG" .

      - name: Building celery container
        run: |
          docker buildx build \
            ${{ steps.prepare.outputs.buildx_args }} \
            -f "docker/Dockerfile.celery" \
            -t "screenly/srly-ose-celery:$DOCKER_TAG" .

      - name: Building redis container
        run: |
          docker buildx build \
            ${{ steps.prepare.outputs.buildx_args }} \
            -f "docker/Dockerfile.redis" \
            -t "screenly/srly-ose-redis:$DOCKER_TAG" .

      - name: Building websocket container
        run: |
          docker buildx build \
            ${{ steps.prepare.outputs.buildx_args }} \
            -f "docker/Dockerfile.websocket" \
            -t "screenly/srly-ose-websocket:$DOCKER_TAG" .

      - name: Building nginx container
        run: |
          docker buildx build \
            ${{ steps.prepare.outputs.buildx_args }} \
            -f "docker/Dockerfile.nginx" \
            -t "screenly/srly-ose-nginx:$DOCKER_TAG" .

      #- name: Building viewer container
      #  run: |
      #    docker buildx build \
      #      ${{ steps.prepare.outputs.buildx_args }} \
      #      --build-arg "PI_VERSION=$pi_version" \
      #      -f docker/Dockerfile.viewer \
      #      -t "screenly/srly-ose-viewer:$DOCKER_TAG-$pi_version" .
